module Main in examples;

@Start
defun main (args : String[]) : void
{
    # This example shows that an exception can cause an invocation to terminate early.

    try
    {
        F::println ("before");

        Main::trouble();

        F::println ("after");
    }
    catch (ex : Exception)
    {
        F::println ("handle");
    }
}

defun trouble () : void
{
    F::println ("enter");

    throw new Exception();

    F::println ("exit");
}